version: "3.2"
services:
  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/home/jovyan/work
